version: 1.5.8.{build}
environment:
  TOKEN:
    secure: q0BlAHGaXBHcTnpUAPIpokRp12G6AsuiT3zBD3RZ7jUCuSziCYTvn4aYTrNzhNQ3

platform:
  - x64

build_script:
  - ps: >-
      $env:NOMAD_VERSION = ($env:APPVEYOR_BUILD_VERSION | ? {$_ -match('^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-rc\d+)?')} | select @{L="Matches";E={$matches[0]}}).matches;
      cmd /c download.bat;
      choco pack nomad.nuspec

deploy_script:
  - ps: >-
      $version = $env:APPVEYOR_BUILD_VERSION -replace('\.\d*$');
      choco apiKey -k $env:TOKEN -source https://push.chocolatey.org/;
      choco push nomad.$version.nupkg --source https://push.chocolatey.org/

artifacts:
  - path: '**\*.nupkg'
